// <auto-generated />
using System;
using ChallengeErp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChallengeErp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912230734_AddUnitOfMeasure")]
    partial class AddUnitOfMeasure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ChallengeErp.Api.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "OC-1001",
                            Provider = "Vidrios del Sureste",
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("ChallengeErp.Api.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "Vidrio flotado 6 mm",
                            OrderId = "OC-1001",
                            Price = 180.00m,
                            Quantity = 100m,
                            UnitOfMeasure = "m2"
                        },
                        new
                        {
                            Id = 2,
                            Article = "Silicón estructural",
                            OrderId = "OC-1001",
                            Price = 95.00m,
                            Quantity = 40m,
                            UnitOfMeasure = "pza"
                        },
                        new
                        {
                            Id = 3,
                            Article = "Perfil de aluminio 3 m",
                            OrderId = "OC-1001",
                            Price = 310.00m,
                            Quantity = 25m,
                            UnitOfMeasure = "pza"
                        });
                });

            modelBuilder.Entity("ChallengeErp.Api.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderLineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ChallengeErp.Api.Entities.OrderLine", b =>
                {
                    b.HasOne("ChallengeErp.Api.Entities.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ChallengeErp.Api.Entities.Receipt", b =>
                {
                    b.HasOne("ChallengeErp.Api.Entities.OrderLine", "OrderLine")
                        .WithMany("Receipts")
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderLine");
                });

            modelBuilder.Entity("ChallengeErp.Api.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ChallengeErp.Api.Entities.OrderLine", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
